vich_uploader:
    db_driver: orm

    mappings:
       articles:
           uri_prefix: '%articles%'
           upload_destination: '%kernel.project_dir%/public%articles%'
           namer : Vich\UploaderBundle\Naming\SmartUniqueNamer
